{% set version = '0.3.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spdata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spData_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spData/spData_{{ version }}.tar.gz
  sha256: 7c7d93e7b722e67695f89e1961592733393298229359768fe846087b73d615a4

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('spData')"           # [not win]
    - "\"%R%\" -e \"library('spData')\""  # [win]

about:
  home: https://nowosad.github.io/spData/
  license: CC0
  summary: Diverse spatial datasets for demonstrating, benchmarking and teaching spatial data
    analysis. It includes R data of class sf (defined by the package 'sf'), Spatial
    ('sp'), and nb ('spdep'). Unlike other spatial data packages such as 'rnaturalearth'
    and 'maps', it also contains data stored in a range of file formats including GeoJSON,
    ESRI Shapefile and GeoPackage. Some of the datasets are designed to illustrate specific
    analysis techniques. cycle_hire() and cycle_hire_osm(), for example, is designed
    to illustrate point pattern analysis techniques.
  license_family: CC

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: spData
# Title: Datasets for Spatial Analysis
# Version: 0.3.2
# Authors@R: c(person("Roger", "Bivand", role = "aut", email="Roger.Bivand@nhh.no", comment = c(ORCID = "0000-0003-2392-6140")), person("Jakub", "Nowosad", role = c("aut", "cre"), email="nowosad.jakub@gmail.com", comment = c(ORCID = "0000-0002-1057-3721")), person("Robin", "Lovelace", role = "aut", comment = c(ORCID = "0000-0001-5679-6536")), person("Mark", "Monmonier", role = "ctb", comment = "author of the state.vbm dataset"), person("Greg", "Snow", role = "ctb", comment = "author of the state.vbm dataset") )
# Description: Diverse spatial datasets for demonstrating, benchmarking and teaching spatial data analysis. It includes R data of class sf (defined by the package 'sf'), Spatial ('sp'), and nb ('spdep'). Unlike other spatial data packages such as 'rnaturalearth' and 'maps', it also contains data stored in a range of file formats including GeoJSON, ESRI Shapefile and GeoPackage. Some of the datasets are designed to illustrate specific analysis techniques. cycle_hire() and cycle_hire_osm(), for example, is designed to illustrate point pattern analysis techniques.
# Depends: R (>= 3.3.0)
# Suggests: foreign, maptools, raster, rgdal, sf, sp, spDataLarge (>= 0.3.0), spdep, spatialreg
# License: CC0
# RoxygenNote: 6.1.1
# LazyData: true
# URL: https://nowosad.github.io/spData/
# BugReports: https://github.com/Nowosad/spData/issues
# Additional_repositories: https://nowosad.github.io/drat
# NeedsCompilation: no
# Packaged: 2019-09-19 11:13:43 UTC; jn
# Author: Roger Bivand [aut] (<https://orcid.org/0000-0003-2392-6140>), Jakub Nowosad [aut, cre] (<https://orcid.org/0000-0002-1057-3721>), Robin Lovelace [aut] (<https://orcid.org/0000-0001-5679-6536>), Mark Monmonier [ctb] (author of the state.vbm dataset), Greg Snow [ctb] (author of the state.vbm dataset)
# Maintainer: Jakub Nowosad <nowosad.jakub@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-09-19 12:10:02 UTC
