appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: NMCJDSuak31VbO3PDc7xQVCI54QAxBLL9ezn0IePmjplx9XA1Rz0+iTyqSl/3FdoDVg5EwRiEkunYYi62MmRylZFiqy2JDtns/7Q5zLxipEOFa2mveRhgucDu3n42QpmIs7rSaSjDVwzyff/E/8Jg5FSYNqWo0pnrN3ajBhb6gp3tX3V1pQGFZwcrNxwb1WxH63YJGdDbuUvwy56nFucr1VytMQMJAsXjOXqP4a9qjoCuhQwHx6A86gcFXyytYEAyj44rMcl9xWWOkCMX6ICiUS6c8gzP40n45p749mGKUYT91hWpW2d8onxYv5pnso6n111C6cG3jLBQbacdZlFEGudsdUE8P5nQoJ0J1ztJL4NY0DkV4ZHE5B4L7ueOYQZjI+cXmH929t1QllNg+SeoTWX7p4c8mzwwnXBekDOHHdqTY+QCsa6n629a0LUPTvE93yifImlHX2LdXsVC8ByI/h1c/vjn6UokRPNDf3kjZtHGKL/Zoma+M0hJCBbWcbxNu3jgVFYtmNbrpPRupxNU+EoYgiOvnlhXV0IzpiGEQKANIRbPOWds/lhaW/R1Tjuzbd9kLIeIAlsLD8wwZAzp1DWXEr4h9UPasajZYukKSbFJ96kQ5WcbI3babzMMei2unKcR7d15No9ILoyBrobom/Nz6XqAKmnhaZCZzSwoco=}
